### ISSUE TITLE
symbol_database

### ISSUE THREAD

**Issue by RamonBeast** [GreatFruitOmsk/protobuf-py3#9]
Hi,

I'm trying to do access a protobuf using python3 and I get an error on this line:

```from google.protobuf import symbol_database as _symbol_database```

symbol_database appears not to be there, do you have any suggestion on how to proceed (if possible)?

Thanks

**Comment by Kentzo** [comment]
I suggest to use the official protobuf instead.

Best Regards
Ilya Kulakov
